### ISSUE TITLE
 spyder-unittest hangs

### ISSUE THREAD

**Issue by raczben** [spyder-ide/spyder-unittest#136] opened 2020-01-22 11:00 UTC
## Description of your problem
spyder-unittest totally hangs. The full Spyder IDE freezes, when I start my unittests. The tests never finished, whats more cannot they be stopped with the red square-button. All tests run and finish (some passes, some fails) in terminal, using `python -m unittest` command

## What steps will reproduce the problem?
I test [wexpect](https://github.com/raczben/wexpect/tree/9807ad5ebc72d71038046b191a029d42c2d6fda1) so I suggest to download, and try to run tests of this module, however, I will try to reduce the issue to help the reproduction.

## What is the expected output? What do you see instead?
Not to hang (or at least should be stopped with the red square)

## Key versions and other information:

* Spyder version: 3.3.6
* Version of spyder-unittest plugin: 0.4.0
* Installation method for Spyder and the unittest plugin: Anaconda
* Python version: Python 3.7.4
* Testing framework used:  unittest
* Testing framework version: Dont know, built-in
* Operating system: Win10 10.0.18363 Build 18363

**Comment by jitseniesen** [comment] 2020-01-22 13:40
Thanks for the report. I don't have access to Windows at the moment, so I can't run the tests of wexpect. Could you please run `python -m unittest discover -v` in the terminal and copy the output? I suspect that Spyder hangs when trying to parse this output.

Looking at the versions you reported, spyder-unittest 0.4.0 and spyder 3.3.6 are not meant to be used together and Anaconda should prevent this. Can you please double check the version numbers?

**Comment by jitseniesen** [comment] 2020-02-20 14:08
Closing because it is not followed up. May be duplicate of #129.

**Closed by jitseniesen** 2020-02-20 14:08 UTC
